### ISSUE TITLE
trustgraph+flaggraph or trustgraph with negative values for flags?

### ISSUE THREAD

**Issue by dominictarr** [ssbc/phoenix#257]
Currently the flag graph and the trust graph are separate datastructures.
I'm thinking that maybe we should adjust this so that flags are represented as a negatively weighted trust edge.
This would require updating our current algorithm, which is based on pagerank, and only uses positive edges (because you cannot create negative links on the web)

I don't think a flag graph is useful in the same way, friend-of-a-friend is stronger than enemy-of-an-enemy. So, I don't really care who the people I think are jerks think are jerks, but i do care if my friends think someone is a jerk.

**Comment by pfraze** [comment]
yeah, for flags all i need in the UI is to know who the local user has flagged and who the trusted users have flagged

currently we have trust/untrust and flag/unflag messages. we could try something that combines them...

`{ type: 'trust', value: 1, rel: 'trusts', feed: <hash> }` trusts
`{ type: 'trust', value: 0, rel: 'trusts', feed: <hash> }` nothings
`{ type: 'trust', value: -1, rel: 'trusts', feed: <hash> }` flags

**Comment by dominictarr** [comment]
yeah, that looks good, although zero weight would probably be the same as not having an edge.

**Comment by pfraze** [comment]
yeah that's the idea. i need something for when you untrust / unflag

**Comment by ahdinosaur** [comment]
+1

**Comment by dominictarr** [comment]
got it. yeah that makes sense.

**Comment by pfraze** [comment]
in sbot's friends plugin, going to remove the flags graph and put the trust value in the edge's data. if the value is 0, i'll delete the edge

**Comment by pfraze** [comment]
using `rel: trusts` for all messages, even if `value: -1`, is feeling like a bad idea to me now. 'trusts' seems like it suggests `value: 1`

maybe we should consider a generalized rel for users pinning data on other users, such as `assigns`? in which case we'd have

`{ type: 'trust', rel: 'assigns', value: -1/0/1, feed: ... }`

and it would also work for names

`{ type: 'name', rel: 'assigns', name: ..., feed: ... }` instead of
`{ type: 'name', rel: 'names', name: ..., feed: ... }`

and probably others 

`{ type: 'profile-pic', rel: 'assigns', ext: ..., feed: ... }`

**Comment by dominictarr** [comment]
you are taking the rel name too literally. It just has to suggest the meaning. it takes only a sentence to explain that positive trust is good and negative trust is bad.

setting the `rel` to always be `'assigns'` and use `type` just shifts the meaning that `rel` had to `type`.

**Comment by pfraze** [comment]
yeah, if youre not into that idea then i guess we can stick with `rel: trusts`

**Comment by pfraze** [comment]
https://github.com/ssbc/scuttlebot/pull/70

**Comment by dominictarr** [comment]
hmm, after thinking about this more, I realized that the pagerank "random surfer" model dosen't make sense anymore if we have negative links - because what does the negative link mean? does the surfer unclick on it?

I have a few ideas about how to interpret this, but I need to drink a coffee and think about it more.

**Comment by pfraze** [comment]
could you define your range of probability to include the negatives (eg -1 to 1, so -1 is 0% and 1 is 100%)? we'd then define our thresholds of trust as eg `>=0.5`, which translates to links with `>=75%` odds of clicking

**Comment by dominictarr** [comment]
That changes the interpretation significantly. It would only make a small difference to the positive link model, and have much effect on the probability of following a negative link, compared to just being an absense of a link.

**Comment by reqshark** [comment]
Wtf is a negative link? Pardon my French.

**Comment by pfraze** [comment]
when you flag another user, ssb publishes a link from your feed to the target's with a negative trust value

**Comment by reqshark** [comment]
damn that's some cold hearted shit. i think being explicit, (providing such an oportunity, a.k.a. downvote) is more generally a regrettable admission in a moment of personal weakness. 

instead be greatful some random motherfuckin upstream provider connected etherlink downstream to your location. whatever that's not the point. the point, is, however: do not support haters and haterish vengance. it servers no one. not even the hater. 

(a) hatred dilutes the energy of the person administering justice

(b) i am slightly drunk at this juncture and offer out a personal gaurantee that thi9ngs said while struggling for concentration are often regrettableeee

**Comment by pfraze** [comment]
haha, i feel ya

we've got flagging in so we can identify malicious users (attackers). since there's no central authority, the users have to trust each other with decisions. sometimes those decisions can be security critical, so we need a way to warn people about bad actors

encryption is a pretty good example of a security-critical decision. if i'm trying to encrypt a message for you, i have to be sure i'm using your public key and not the public key of somebody posing as @reqshark . with flagging, if my friends catch somebody posing as you, they could warn me with a flag

**Comment by reqshark** [comment]
@pfraze i trust you. i trust @dominictarr more than that mofo ryan dahl himself. what more can i say
