### ISSUE TITLE
Who is this identity I see?

### ISSUE THREAD

**Issue by kumavis** [ssbc/phoenix#279]
under connections:
![screen shot 2015-01-20 at 11 14 47](https://cloud.githubusercontent.com/assets/1474978/5824216/e4220f3a-a097-11e4-923d-4fafe7f4fb98.png)

profile closeup: 
![screen shot 2015-01-20 at 11 13 52](https://cloud.githubusercontent.com/assets/1474978/5824217/e422f206-a097-11e4-990c-95adbc27d604.png)

**Comment by kumavis** [comment]
seems like it should be grimwire.com
is there a seperate identity for the server connection and the server status feed?
or is this the new grimwire.com server?

**Comment by pfraze** [comment]
i gave grimwire a new identity (which that is) so that can contribute to the confusion here

what's strange is that you don't have any messages for it -- otherwise you'd see the name it gave itself. i follow grim, so you should be reqeusting its messages.

try following it and seeing if its messages start to populate

**Comment by pfraze** [comment]
turns out kumavis wasnt following the account or any user that did, so he wasnt getting the messages

behaving as expected
